import { Product, PipelineStage, Filters } from "./types";

export const defaultPipelineStages: PipelineStage[] = [
  { id: "intent", name: "Intent", icon: "brain", status: "pending", statusText: "" },
  { id: "search", name: "Search", icon: "search", status: "pending", statusText: "" },
  { id: "trust", name: "Trust", icon: "shield", status: "pending", statusText: "" },
  { id: "price", name: "Price", icon: "dollar", status: "pending", statusText: "" },
  { id: "negotiate", name: "Negotiate", icon: "handshake", status: "pending", statusText: "" },
];

export const defaultFilters: Filters = {
  budgetRange: [0, 1200],
  brands: [],
  condition: "Any",
  mustHaveFeatures: [],
  niceToHaveFeatures: [],
  platforms: ["Amazon", "eBay", "Walmart", "Best Buy"],
  sort: "relevance",
};

const generatePriceHistory = (basePrice: number): { date: string; price: number }[] => {
  const history = [];
  for (let i = 90; i >= 0; i -= 7) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    const variation = (Math.random() - 0.5) * basePrice * 0.15;
    history.push({
      date: date.toISOString().split("T")[0],
      price: Math.round((basePrice + variation) * 100) / 100,
    });
  }
  return history;
};

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Sony ZV-E10 Mirrorless Camera with 16-50mm Lens Kit",
    brand: "Sony",
    image: "https://picsum.photos/300/300?random=1",
    rating: 4.7,
    reviewCount: 2341,
    platform: "Amazon",
    url: "https://amazon.com/example",
    specs: {
      Sensor: "24.2MP APS-C CMOS",
      "ISO Range": "100-32000 (expandable to 51200)",
      Autofocus: "425 phase-detect AF points",
      Video: "4K 30fps, 1080p 120fps",
      Weight: "343g (body only)",
      Screen: '3.0" vari-angle touchscreen',
      "Battery Life": "~440 shots per charge",
      Connectivity: "Wi-Fi, Bluetooth, USB-C, Mic input",
    },
    features: ["4K Video", "Vlogging", "Lightweight", "Directional Mic", "Vari-angle Screen"],
    condition: "New",
    trust: {
      overall: 94,
      sellerScore: 97,
      reviewAuthenticity: 91,
      productLegitimacy: 95,
      flags: [
        { severity: "info", text: "Authorized Sony dealer" },
        { severity: "info", text: "30-day return policy verified" },
      ],
      sourcesChecked: [
        { name: "Amazon Seller DB", url: "#" },
        { name: "Fakespot", url: "#" },
        { name: "ReviewMeta", url: "#" },
      ],
    },
    price: {
      originalPrice: 698,
      effectivePrice: 598,
      savings: 100,
      savingsBreakdown: "Save $70 sale + $20 coupon + $10 cashback",
      priceHistory: generatePriceHistory(698),
      competitorPrices: [
        { platform: "Amazon", price: 628, inStock: true, url: "#" },
        { platform: "Best Buy", price: 698, inStock: true, url: "#" },
        { platform: "eBay", price: 579, inStock: true, url: "#" },
        { platform: "Walmart", price: 678, inStock: false, url: "#" },
      ],
      coupons: [{ code: "SONY20", description: "$20 off Sony cameras", discount: "$20" }],
      cashback: [
        { provider: "Rakuten", percentage: 2, url: "#" },
        { provider: "TopCashback", percentage: 1.5, url: "#" },
      ],
      dealQuality: "Great Deal",
    },
    negotiation: {
      viable: false,
      explanation: "Amazon does not support direct negotiation, but price tracking shows this is near the 90-day low.",
      messages: { aggressive: "", moderate: "", friendly: "" },
      nextSteps: ["Set a price alert for drops below $550", "Check for warehouse deals"],
      expectedCounterRange: { low: 0, high: 0 },
      walkAwayPrice: 0,
    },
    rankingExplanation: { quality: 92, price: 88, brand: 95, reviews: 88 },
  },
  {
    id: "2",
    name: "Fujifilm X-S20 Mirrorless Camera Body",
    brand: "Fujifilm",
    image: "https://picsum.photos/300/300?random=2",
    rating: 4.8,
    reviewCount: 1243,
    platform: "Best Buy",
    url: "https://bestbuy.com/example",
    specs: {
      Sensor: "26.1MP APS-C X-Trans CMOS 5 HR",
      "ISO Range": "125-12800 (expandable to 51200)",
      Autofocus: "425 points hybrid AF with AI subject detection",
      Video: "6.2K 30fps, 4K 60fps",
      Weight: "491g (body only)",
      Screen: '3.0" vari-angle touchscreen',
      "Battery Life": "~800 shots per charge",
      "Film Simulations": "19 modes including Nostalgic Neg",
    },
    features: ["Film Simulations", "6.2K Video", "AI Subject Detection", "USB-C Charging", "IBIS"],
    condition: "New",
    trust: {
      overall: 97,
      sellerScore: 99,
      reviewAuthenticity: 95,
      productLegitimacy: 97,
      flags: [
        { severity: "info", text: "Official Best Buy listing" },
        { severity: "info", text: "Manufacturer warranty included" },
      ],
      sourcesChecked: [
        { name: "Best Buy Verified", url: "#" },
        { name: "Fakespot", url: "#" },
      ],
    },
    price: {
      originalPrice: 1299,
      effectivePrice: 1149,
      savings: 150,
      savingsBreakdown: "Save $100 sale + $30 coupon + $20 rewards",
      priceHistory: generatePriceHistory(1299),
      competitorPrices: [
        { platform: "Best Buy", price: 1199, inStock: true, url: "#" },
        { platform: "Amazon", price: 1249, inStock: true, url: "#" },
        { platform: "eBay", price: 1099, inStock: true, url: "#" },
      ],
      coupons: [{ code: "FUJI30", description: "$30 off Fujifilm cameras", discount: "$30" }],
      cashback: [{ provider: "Rakuten", percentage: 1, url: "#" }],
      dealQuality: "Good Deal",
    },
    negotiation: {
      viable: false,
      explanation: "Best Buy has a price match guarantee. Use eBay price ($1099) for a price match request.",
      messages: { aggressive: "", moderate: "", friendly: "" },
      nextSteps: ["Use eBay price for a price match request", "Check open-box deals at local stores"],
      expectedCounterRange: { low: 0, high: 0 },
      walkAwayPrice: 0,
    },
    rankingExplanation: { quality: 95, price: 72, brand: 92, reviews: 90 },
  },
  {
    id: "3",
    name: "Canon EOS R100 Mirrorless Camera with RF-S 18-45mm Lens",
    brand: "Canon",
    image: "https://picsum.photos/300/300?random=3",
    rating: 4.3,
    reviewCount: 3102,
    platform: "Amazon",
    url: "https://amazon.com/example2",
    specs: {
      Sensor: "24.1MP APS-C CMOS",
      "ISO Range": "100-12800 (expandable to 25600)",
      Autofocus: "Dual Pixel CMOS AF with Eye AF",
      Video: "4K 24fps, 1080p 60fps",
      Weight: "356g (body only)",
      Screen: '3.0" fixed LCD',
      "Battery Life": "~340 shots per charge",
      Connectivity: "Wi-Fi, Bluetooth",
    },
    features: ["Beginner Friendly", "Eye AF", "4K Video", "Ultra Lightweight", "RF Mount"],
    condition: "New",
    trust: {
      overall: 91,
      sellerScore: 93,
      reviewAuthenticity: 87,
      productLegitimacy: 94,
      flags: [
        { severity: "info", text: "Ships from Amazon" },
        { severity: "warning", text: "12% of reviews may be incentivized" },
      ],
      sourcesChecked: [
        { name: "Amazon Seller DB", url: "#" },
        { name: "ReviewMeta", url: "#" },
        { name: "Fakespot", url: "#" },
      ],
    },
    price: {
      originalPrice: 479,
      effectivePrice: 399,
      savings: 80,
      savingsBreakdown: "Save $60 sale + $15 coupon + $5 cashback",
      priceHistory: generatePriceHistory(479),
      competitorPrices: [
        { platform: "Amazon", price: 419, inStock: true, url: "#" },
        { platform: "Walmart", price: 449, inStock: true, url: "#" },
        { platform: "Best Buy", price: 449, inStock: true, url: "#" },
        { platform: "eBay", price: 389, inStock: true, url: "#" },
      ],
      coupons: [{ code: "CANON15", description: "$15 off Canon cameras", discount: "$15" }],
      cashback: [{ provider: "Honey", percentage: 1.5, url: "#" }],
      dealQuality: "Great Deal",
    },
    negotiation: {
      viable: false,
      explanation: "Fixed marketplace pricing. Best approach is coupon stacking.",
      messages: { aggressive: "", moderate: "", friendly: "" },
      nextSteps: ["Stack CANON15 coupon with cashback for maximum savings"],
      expectedCounterRange: { low: 0, high: 0 },
      walkAwayPrice: 0,
    },
    rankingExplanation: { quality: 78, price: 95, brand: 88, reviews: 82 },
  },
  {
    id: "4",
    name: "Sony Alpha a6400 Mirrorless Camera with 16-50mm & 55-210mm Lenses",
    brand: "Sony",
    image: "https://picsum.photos/300/300?random=4",
    rating: 4.5,
    reviewCount: 1567,
    platform: "eBay",
    url: "https://ebay.com/example",
    specs: {
      Sensor: "24.2MP APS-C CMOS",
      "ISO Range": "100-32000",
      Autofocus: "425 phase-detect AF points",
      Video: "4K 30fps",
      Weight: "403g (body only)",
      Screen: '3.0" tilting touchscreen',
      "Battery Life": "~410 shots per charge",
      Includes: "16-50mm + 55-210mm lenses",
    },
    features: ["Dual Lens Kit", "4K Video", "Fast AF", "Compact", "Great for Beginners"],
    condition: "Refurbished",
    trust: {
      overall: 78,
      sellerScore: 72,
      reviewAuthenticity: 80,
      productLegitimacy: 82,
      flags: [
        { severity: "warning", text: "Seller has 94.5% positive rating (below 97% threshold)" },
        { severity: "warning", text: "Refurbished — verify warranty terms" },
        { severity: "info", text: "eBay Money Back Guarantee applies" },
      ],
      sourcesChecked: [
        { name: "eBay Seller History", url: "#" },
        { name: "Third-party verification", url: "#" },
      ],
    },
    price: {
      originalPrice: 998,
      effectivePrice: 649,
      savings: 349,
      savingsBreakdown: "Save $299 refurb discount + $35 coupon + $15 cashback",
      priceHistory: generatePriceHistory(800),
      competitorPrices: [
        { platform: "eBay", price: 684, inStock: true, url: "#" },
        { platform: "Amazon", price: 998, inStock: true, url: "#" },
        { platform: "Best Buy", price: 998, inStock: false, url: "#" },
      ],
      coupons: [{ code: "SAVE15EBAY", description: "15% off select electronics", discount: "15%" }],
      cashback: [{ provider: "Rakuten", percentage: 2.5, url: "#" }],
      dealQuality: "Great Deal",
    },
    negotiation: {
      viable: true,
      explanation: "This eBay listing has 'Make an Offer' enabled. The seller has been listing for 23 days and has 4 watchers. Historical data suggests offers at 85-90% of asking price are typically accepted.",
      messages: {
        aggressive: "Hi, I'm interested in the Sony a6400 dual lens kit. I've found similar refurbished units going for $560-$590 on other platforms. Given the refurbished condition and comparable market pricing, I'd like to offer $570. I'm ready to pay immediately.",
        moderate: "Hello! I'm very interested in your Sony a6400 bundle. I've been comparing prices across several retailers and noticed similar refurbished kits priced around $590-$620. Would you consider $600? I can complete the purchase today.",
        friendly: "Hi there! Love this dual lens kit listing. I'm a photography student working with a tight budget. Would you be open to $620? I've been eyeing this for a while and would really appreciate any flexibility. Happy to leave a great review!",
      },
      nextSteps: [
        "Start with the moderate offer ($600)",
        "If rejected, follow up with $630 within 24 hours",
        "Mention you can pay immediately to increase acceptance odds",
        "If counter-offered above $660, consider the aggressive approach",
      ],
      expectedCounterRange: { low: 620, high: 660 },
      walkAwayPrice: 670,
    },
    rankingExplanation: { quality: 82, price: 95, brand: 90, reviews: 75 },
  },
  {
    id: "5",
    name: "Panasonic Lumix G85 4K Mirrorless Camera with 12-60mm Lens",
    brand: "Panasonic",
    image: "https://picsum.photos/300/300?random=5",
    rating: 4.4,
    reviewCount: 2815,
    platform: "Walmart",
    url: "https://walmart.com/example",
    specs: {
      Sensor: "16MP Micro Four Thirds Live MOS",
      "ISO Range": "200-25600",
      Autofocus: "49-area contrast AF + DFD",
      Video: "4K 30fps UHD",
      Weight: "453g (body only)",
      Screen: '3.0" free-angle OLED',
      Stabilization: "5-axis Dual I.S.",
      Viewfinder: "2,360k-dot OLED EVF",
    },
    features: ["Dual I.S.", "Weather Sealed", "4K Photo Mode", "Free-angle Screen", "Silent Shutter"],
    condition: "New",
    trust: {
      overall: 88,
      sellerScore: 90,
      reviewAuthenticity: 85,
      productLegitimacy: 90,
      flags: [
        { severity: "info", text: "Sold by Walmart directly" },
        { severity: "info", text: "Free 90-day returns" },
      ],
      sourcesChecked: [
        { name: "Walmart Verified", url: "#" },
        { name: "Fakespot", url: "#" },
      ],
    },
    price: {
      originalPrice: 797,
      effectivePrice: 697,
      savings: 100,
      savingsBreakdown: "Save $60 sale + $20 Walmart+ perk + $20 cashback",
      priceHistory: generatePriceHistory(797),
      competitorPrices: [
        { platform: "Walmart", price: 737, inStock: true, url: "#" },
        { platform: "Amazon", price: 797, inStock: true, url: "#" },
        { platform: "eBay", price: 649, inStock: true, url: "#" },
        { platform: "Best Buy", price: 797, inStock: false, url: "#" },
      ],
      coupons: [],
      cashback: [{ provider: "Walmart+", percentage: 5, url: "#" }],
      dealQuality: "Good Deal",
    },
    negotiation: {
      viable: false,
      explanation: "Walmart does not support negotiation. Consider their price match policy.",
      messages: { aggressive: "", moderate: "", friendly: "" },
      nextSteps: ["Use eBay price ($649) for Walmart price match"],
      expectedCounterRange: { low: 0, high: 0 },
      walkAwayPrice: 0,
    },
    rankingExplanation: { quality: 80, price: 82, brand: 75, reviews: 82 },
  },
  {
    id: "6",
    name: "Nikon Z50 Mirrorless Camera with 16-50mm VR Lens",
    brand: "Nikon",
    image: "https://picsum.photos/300/300?random=6",
    rating: 4.6,
    reviewCount: 1432,
    platform: "Best Buy",
    url: "https://bestbuy.com/example2",
    specs: {
      Sensor: "20.9MP APS-C CMOS",
      "ISO Range": "100-51200 (expandable to 204800)",
      Autofocus: "209-point hybrid AF",
      Video: "4K 30fps UHD",
      Weight: "395g (body only)",
      Screen: '3.2" tilting touchscreen',
      "Battery Life": "~320 shots per charge",
      Connectivity: "Wi-Fi, Bluetooth, USB-C",
    },
    features: ["Eye-Detection AF", "20 fps Shooting", "4K Video", "SnapBridge", "Excellent Ergonomics"],
    condition: "New",
    trust: {
      overall: 95,
      sellerScore: 98,
      reviewAuthenticity: 93,
      productLegitimacy: 95,
      flags: [
        { severity: "info", text: "Authorized Nikon dealer" },
        { severity: "info", text: "Extended holiday return policy" },
      ],
      sourcesChecked: [
        { name: "Best Buy Verified", url: "#" },
        { name: "Fakespot", url: "#" },
      ],
    },
    price: {
      originalPrice: 796,
      effectivePrice: 696,
      savings: 100,
      savingsBreakdown: "Save $60 sale + $25 coupon + $15 rewards",
      priceHistory: generatePriceHistory(796),
      competitorPrices: [
        { platform: "Best Buy", price: 736, inStock: true, url: "#" },
        { platform: "Amazon", price: 756, inStock: true, url: "#" },
        { platform: "eBay", price: 699, inStock: true, url: "#" },
        { platform: "Walmart", price: 796, inStock: true, url: "#" },
      ],
      coupons: [{ code: "NIKON25", description: "$25 off Nikon cameras", discount: "$25" }],
      cashback: [{ provider: "TopCashback", percentage: 2, url: "#" }],
      dealQuality: "Good Deal",
    },
    negotiation: {
      viable: false,
      explanation: "Best Buy price match available. Currently within $40 of the all-time low.",
      messages: { aggressive: "", moderate: "", friendly: "" },
      nextSteps: ["Request price match with eBay listing ($699)"],
      expectedCounterRange: { low: 0, high: 0 },
      walkAwayPrice: 0,
    },
    rankingExplanation: { quality: 88, price: 82, brand: 92, reviews: 84 },
  },
  {
    id: "7",
    name: "Olympus OM-D E-M10 Mark IV with 14-42mm EZ Lens",
    brand: "Olympus",
    image: "https://picsum.photos/300/300?random=7",
    rating: 4.5,
    reviewCount: 987,
    platform: "Amazon",
    url: "https://amazon.com/example3",
    specs: {
      Sensor: "20MP Micro Four Thirds Live MOS",
      "ISO Range": "200-25600",
      Autofocus: "121-point contrast AF",
      Video: "4K 30fps",
      Weight: "383g (body only)",
      Stabilization: "5-axis in-body (4.5 stops)",
      Screen: '3.0" tilting touchscreen',
      Connectivity: "Wi-Fi, Bluetooth",
    },
    features: ["In-Body Stabilization", "Ultra Compact", "Selfie Screen", "Art Filters", "USB Charging"],
    condition: "New",
    trust: {
      overall: 92,
      sellerScore: 95,
      reviewAuthenticity: 90,
      productLegitimacy: 91,
      flags: [{ severity: "info", text: "Authorized dealer with warranty" }],
      sourcesChecked: [
        { name: "Amazon Seller DB", url: "#" },
        { name: "Fakespot", url: "#" },
      ],
    },
    price: {
      originalPrice: 699,
      effectivePrice: 599,
      savings: 100,
      savingsBreakdown: "Save $70 sale + $20 coupon + $10 cashback",
      priceHistory: generatePriceHistory(699),
      competitorPrices: [
        { platform: "Amazon", price: 629, inStock: true, url: "#" },
        { platform: "Best Buy", price: 699, inStock: true, url: "#" },
        { platform: "eBay", price: 569, inStock: true, url: "#" },
      ],
      coupons: [{ code: "OLYMP20", description: "$20 off Olympus cameras", discount: "$20" }],
      cashback: [{ provider: "Rakuten", percentage: 3, url: "#" }],
      dealQuality: "Good Deal",
    },
    negotiation: {
      viable: false,
      explanation: "Standard Amazon pricing. Watch for Lightning Deals.",
      messages: { aggressive: "", moderate: "", friendly: "" },
      nextSteps: ["Set CamelCamelCamel price alert for drops below $560"],
      expectedCounterRange: { low: 0, high: 0 },
      walkAwayPrice: 0,
    },
    rankingExplanation: { quality: 85, price: 82, brand: 80, reviews: 80 },
  },
  {
    id: "8",
    name: "Canon EOS M50 Mark II with 15-45mm IS STM Lens - Used",
    brand: "Canon",
    image: "https://picsum.photos/300/300?random=8",
    rating: 4.2,
    reviewCount: 892,
    platform: "eBay",
    url: "https://ebay.com/example2",
    specs: {
      Sensor: "24.1MP APS-C CMOS",
      "ISO Range": "100-25600 (expandable to 51200)",
      Autofocus: "Dual Pixel CMOS AF",
      Video: "4K 24fps, 1080p 120fps",
      Weight: "387g (body only)",
      Screen: '3.0" vari-angle touchscreen',
      "Battery Life": "~250 shots per charge",
      "Condition Notes": "Excellent condition, minor cosmetic wear on body",
    },
    features: ["Vari-angle Screen", "Eye AF", "4K Video", "Lightweight", "Great for Vlogging"],
    condition: "Used",
    trust: {
      overall: 62,
      sellerScore: 55,
      reviewAuthenticity: 70,
      productLegitimacy: 65,
      flags: [
        { severity: "critical", text: "Seller account is less than 6 months old" },
        { severity: "warning", text: "Limited seller history (23 transactions)" },
        { severity: "warning", text: "No returns accepted" },
        { severity: "info", text: "eBay Money Back Guarantee still applies" },
      ],
      sourcesChecked: [
        { name: "eBay Seller History", url: "#" },
        { name: "Third-party check", url: "#" },
      ],
    },
    price: {
      originalPrice: 599,
      effectivePrice: 335,
      savings: 264,
      savingsBreakdown: "Save $264 vs new (used pricing + coupon)",
      priceHistory: generatePriceHistory(400),
      competitorPrices: [
        { platform: "eBay", price: 348, inStock: true, url: "#" },
        { platform: "Amazon", price: 549, inStock: true, url: "#" },
      ],
      coupons: [{ code: "SAVE15EBAY", description: "15% off select electronics", discount: "15%" }],
      cashback: [],
      dealQuality: "Great Deal",
    },
    negotiation: {
      viable: true,
      explanation: "Make an Offer is enabled. Seller is motivated — listing has been up for 18 days with 2 price reductions already. Likely eager to sell.",
      messages: {
        aggressive: "Hi, I noticed this M50 II has been listed for a while. Given the used condition and current market prices for this model, I'd like to offer $270. I see similar units selling for $280-$300 in completed listings. Ready to pay now.",
        moderate: "Hello! Interested in your Canon M50 II. Based on recent sold listings for similar condition units ($290-$320), would you accept $300? I'm a serious buyer and can pay immediately.",
        friendly: "Hi! I've been looking for an M50 II to start my photography journey. My budget is a bit tight — would you consider $310? I'd really appreciate it and will leave positive feedback right away!",
      },
      nextSteps: [
        "Start with moderate offer ($300)",
        "Mention completed listings data to justify your price",
        "Be ready to meet at $320 if counter-offered",
        "If no response in 48 hours, try the friendly approach at $310",
      ],
      expectedCounterRange: { low: 310, high: 340 },
      walkAwayPrice: 350,
    },
    rankingExplanation: { quality: 65, price: 98, brand: 85, reviews: 70 },
  },
];

export const exampleQueries = [
  "Mirrorless camera under $800",
  "Noise cancelling headphones",
  "4K monitor for coding",
  "Running shoes for flat feet",
];

export const mockFiltersForCamera: Filters = {
  budgetRange: [0, 800],
  brands: ["Sony", "Canon", "Fujifilm", "Nikon", "Panasonic", "Olympus"],
  condition: "Any",
  mustHaveFeatures: ["4K Video", "Lightweight"],
  niceToHaveFeatures: ["Weather Sealed", "In-Body Stabilization", "Tilting Screen"],
  platforms: ["Amazon", "eBay", "Walmart", "Best Buy"],
  sort: "relevance",
};
